const slovickaLekce = {
	1: [
	{ cesky: "volitelný, jiný možný (ne optional)", anglicky: "alternative" },
	{ cesky: "klávesy šipek", anglicky: "arrow keys" },
	{ cesky: "hvězdička", anglicky: "asterisk" },
	{ cesky: "zálohovat (ne store = uložit)", anglicky: "back up" },
	{ cesky: "obrácené lomítko", anglicky: "backslash" },
	{ cesky: "řádkové menu", anglicky: "bar menu" },
	{ cesky: "blikat", anglicky: "blink" },
	{ cesky: "rámeček (ne frame)", anglicky: "box" },
	{ cesky: "přerušit (ne abort, interrupt, suspend)", anglicky: "break" },
	{ cesky: "vestavět, vestavěný", anglicky: "built in" },
	{ cesky: "zrušit, stornovat (ne discard)", anglicky: "cancel" },
	{ cesky: "velké písmeno (ne uppercase)", anglicky: "capital letter" },
	{ cesky: "deska, karta", anglicky: "card" },
	{ cesky: "kapitola", anglicky: "chapter" },
	{ cesky: "znak (ne sign)", anglicky: "character" },
	{ cesky: "vymazat (ne delete, clear, remove)", anglicky: "erase" },
	{ cesky: "zavřít", anglicky: "close" },
	{ cesky: "dvojtečka", anglicky: "colon" },
	{ cesky: "sloupec", anglicky: "column" },
	{ cesky: "čárka ve větě", anglicky: "comma" },
	{ cesky: "zkrátit, vyjmout, vystřihnout", anglicky: "cut" },
	{ cesky: "pomlčka (ne hyphen)", anglicky: "dash" },
	{ cesky: "hustota", anglicky: "density" },
	{ cesky: "tečka, bod (ne point)", anglicky: "dot" },
	{ cesky: "disková mechanika", anglicky: "disk drive" },
	{ cesky: "kopírování (ne copying)", anglicky: "duplication" },
	{ cesky: "upravit text (ne modify, change)", anglicky: "edit" },
	{ cesky: "selhat, nepodařit se", anglicky: "fail" },
	{ cesky: "vada, chyba (ne failure, error, mistake)", anglicky: "fault" },
	{ cesky: "číslice, diagram, obrázek", anglicky: "figure" },
	{ cesky: "najít", anglicky: "find" },
	{ cesky: "všeobecný (ne common, universal)", anglicky: "general" },
	{ cesky: "průvodce (ne wizard)", anglicky: "guide" },
	{ cesky: "skrýt, schovat", anglicky: "hide" },
	{ cesky: "pomlčka (ne dash)", anglicky: "hyphen" },
	{ cesky: "úvod", anglicky: "introduction" },
	{ cesky: "neplatný (ne void)", anglicky: "invalid" },
	{ cesky: "písmeno", anglicky: "letter" },
	{ cesky: "řádek (ne row)", anglicky: "line" },
	{ cesky: "odřádkování", anglicky: "line-feed" },
	{ cesky: "zamknout, znepřístupnit", anglicky: "lock" },
	{ cesky: "vyhledání (ne search)", anglicky: "lookup" },
	{ cesky: "hodit se pasovat", anglicky: "match" },
	{ cesky: "matice", anglicky: "matrix" },
	{ cesky: "příští, další (ne following)", anglicky: "next" },
	{ cesky: "všimnout si", anglicky: "notice" },
	{ cesky: "připojený (tiskárna)", anglicky: "on-line" },
	{ cesky: "přepsat (ne rewrite)", anglicky: "overwrite" },
	{ cesky: "stránka", anglicky: "page" },
	{ cesky: "část (ne portion, section)", anglicky: "part" },
	{ cesky: "sbírat, vybírat (ne select, collect)", anglicky: "pick" },
	{ cesky: "chránit, bránit", anglicky: "protect" },
	{ cesky: "tlačit, stisknout (ne press)", anglicky: "push" },
	{ cesky: "opustit, ukončit (ne cancel, exit)", anglicky: "quit" },
	{ cesky: "opustit (ne quit, cancel, leave)", anglicky: "exit" },
	{ cesky: "připraven", anglicky: "ready" },
	{ cesky: "nahradit", anglicky: "replace" },
	{ cesky: "znovu začít", anglicky: "resume" },
	{ cesky: "zkusit znovu (ne resume)", anglicky: "retry" },
	{ cesky: "přepsat (ne overwrite)", anglicky: "rewrite" },
	{ cesky: "páska (ne tape)", anglicky: "ribbon" },
	{ cesky: "řada, řádek (ne line)", anglicky: "row" },
	{ cesky: "uložit, uschovat (ne store)", anglicky: "save" },
	{ cesky: "hledat (ne search, scan)", anglicky: "seek" },
	{ cesky: "procházet, prohledávat (ne seek)", anglicky: "scan" },
	{ cesky: "vybrat (ne choose, pick)", anglicky: "select" },
	{ cesky: "středník", anglicky: "semicolon" },
	{ cesky: "věta", anglicky: "sentence" },
	{ cesky: "nastavit (ne adjust)", anglicky: "set" },
	{ cesky: "posun, přeřaďovač", anglicky: "shift" },
	{ cesky: "velikost, rozměr", anglicky: "size" },
	{ cesky: "lomítko", anglicky: "slash" },
	{ cesky: "stojící samostatně (ne single)", anglicky: "standalone" },
	{ cesky: "uložit data (ne save), úložiště", anglicky: "store" },
	{ cesky: "zapnout (ne turn on)", anglicky: "switch on" },
	{ cesky: "teplota", anglicky: "temperature" },
	{ cesky: "přepínat (ne switch, swap)", anglicky: "toggle" },
	{ cesky: "téma (ne theme)", anglicky: "topic" },
	{ cesky: "celkový (ne overall, celk. součet)", anglicky: "total" },
	{ cesky: "stopa, sledovat", anglicky: "track" },
	{ cesky: "neautorizovaný", anglicky: "unauthorized" },
	{ cesky: "aktualizovaný (ne refreshed)", anglicky: "updated" },
	{ cesky: "pohled, prohlédnout", anglicky: "view" },
	{ cesky: "dvojkový", anglicky: "binary" },
	{ cesky: "úroveň (ne grade)", anglicky: "level" },
	{ cesky: "nedostatečný", anglicky: "insufficient" },
	{ cesky: "prázdný (ne blank)", anglicky: "empty" },
	{ cesky: "zadat, vložit (ne insert)", anglicky: "enter" },
	{ cesky: "datum", anglicky: "date" },
	{ cesky: "jistý  (ne certain)", anglicky: "sure" },
	{ cesky: "chybět", anglicky: "miss" },
	{ cesky: "neúspěch, závada, porucha (ne faul)", anglicky: "failure" },
	{ cesky: "obnovit (ne restore, update, refresh)", anglicky: "recover" },
	{ cesky: "pokračovat (ne continue, resume)", anglicky: "proceed" },
	{ cesky: "jiný, další (ne other, next)", anglicky: "another" },
	{ cesky: "skrytý", anglicky: "hidden" },
	{ cesky: "více", anglicky: "more" },
	{ cesky: "krátký, stručný (ne short)", anglicky: "brief" },
	{ cesky: "plný, nezkrácený (např. výpis)", anglicky: "full" },
	{ cesky: "přepínat (ne switch, toggle)", anglicky: "swap" },
	{ cesky: "viditelný", anglicky: "visible" },
	{ cesky: "rychlý (ne quick)", anglicky: "fast" },
	{ cesky: "ani, žádný", anglicky: "neither" },
	{ cesky: "dokonce i", anglicky: "even" }
	],
	2: [
	{ cesky: "strom", anglicky: "tree" },
	{ cesky: "adresář s podřízenými adr.", anglicky: "folder hierarchy" },
	{ cesky: "komprimovat (ne pack)", anglicky: "compress" },
	{ cesky: "stisknout (ne push, hit)", anglicky: "press" },
	{ cesky: "jakýkoliv", anglicky: "any" },
	{ cesky: "příkazy šedě (nepřístupné)", anglicky: "dimmed commands" },
	{ cesky: "nepřístupný, nedostupný (ne unreach)", anglicky: "unavailable" },
	{ cesky: "pasivovat zaškrtávací políčko", anglicky: "clear check box" },
	{ cesky: "vybrat zaškrtávací políčko", anglicky: "select check box" },
	{ cesky: "částečně vybrané zaškrtávací políčko", anglicky: "shaded check box" },
	{ cesky: "velikost písma", anglicky: "font size" },
	{ cesky: "velikost písma v bodech", anglicky: "point size" },
	{ cesky: "tučný", anglicky: "bold" },
	{ cesky: "kurzíva", anglicky: "italic" },
	{ cesky: "podtržený (ne underscored)", anglicky: "underlined" },
	{ cesky: "podsazení, dolní index", anglicky: "subscript" },
	{ cesky: "nadsazení, horní index", anglicky: "superscript" },
	{ cesky: "textový kurzor", anglicky: "insertion point" },
	{ cesky: "kurzor myši", anglicky: "mouse pointer" },
	{ cesky: "klávesová zkratka, zástupce", anglicky: "shortcut" },
	{ cesky: "táhni a pusť", anglicky: "drag-and-drop" },
	{ cesky: "posuvník (přetáčecí lišta)", anglicky: "scroll bar" },
	{ cesky: "požadavek, nároky (ne demand)", anglicky: "requirement" },
	{ cesky: "ponechat", anglicky: "leave" },
	{ cesky: "beze změn (ne without change)", anglicky: "intact" },
	{ cesky: "původní, počáteční (ne original)", anglicky: "initial" },
	{ cesky: "doporučovat", anglicky: "recommend" },
	{ cesky: "přinejmenším", anglicky: "at least" },
	{ cesky: "podle potřeby", anglicky: "as needed" },
	{ cesky: "používá se", anglicky: "in use" },
	{ cesky: "ze seznamu", anglicky: "from list" },
	{ cesky: "šetřič obrazovky", anglicky: "screen saver" },
	{ cesky: "velké písmeno (ne capital)", anglicky: "uppercase" },
	{ cesky: "malé písmeno)", anglicky: "lowercase" },
	{ cesky: "stavový řádek, pruh (ne line)", anglicky: "status bar" },
	{ cesky: "přílohy", anglicky: "attachment" },
	{ cesky: "znak konce odstavce", anglicky: "paragraph mark" },
	{ cesky: "výskyt (ne presence)", anglicky: "occurrence" },
	{ cesky: "kontrola", anglicky: "check" },
	{ cesky: "opravit (ne repair)", anglicky: "correct" },
	{ cesky: "nastavit pozici (ne set...)", anglicky: "adjust position" },
	{ cesky: "prázdný řádek (ne empty)", anglicky: "blank line" },
	{ cesky: "vybraný text (ne selected)", anglicky: "highlighted text" },
	{ cesky: "obrysy (ne border)", anglicky: "outline" },
	{ cesky: "přerušit (ne break, abort, suspend)", anglicky: "interrupt" },
	{ cesky: "šablona (styl dokumentu)", anglicky: "template" },
	{ cesky: "popisek (např. obrázku, ne description)", anglicky: "caption" },
	{ cesky: "táhnout (ne pull)", anglicky: "drag" },
	{ cesky: "změnit velikost", anglicky: "resize" },
	{ cesky: "vzhledem k (ne according to)", anglicky: "relative to" },
	{ cesky: "sbalit (nabídku, ne soubor)", anglicky: "collapse" },
	{ cesky: "rozbalit (ne explode)", anglicky: "expand" },
	{ cesky: "povýšit, zvýšit (hierar. úroveň)", anglicky: "promote" },
	{ cesky: "snížit (hierar. úroveň)", anglicky: "demote" },
	{ cesky: "místní nabídka", anglicky: "shortcut menu" },
	{ cesky: "upravit, upravit si (ne modify)", anglicky: "customize" },
	{ cesky: "pravopis", anglicky: "spelling" },
	{ cesky: "korektor překlepů", anglicky: "spell checker" },
	{ cesky: "poznámky (ne notes)", anglicky: "annotations" },
	{ cesky: "souhrnné informace", anglicky: "summary info" },
	{ cesky: "ukázka před tiskem", anglicky: "print preview" },
	{ cesky: "záhlaví, hlavička (ne heading)", anglicky: "header" },
	{ cesky: "pata, patička", anglicky: "footer" },
	{ cesky: "velikost papíru", anglicky: "paper size" },
	{ cesky: "na výšku (orientace)", anglicky: "portrait" },
	{ cesky: "na šířku (orientace)", anglicky: "landscape" },
	{ cesky: "odstavec", anglicky: "paragraph" },
	{ cesky: "zarovnání (odstavce)", anglicky: "alignment" },
	{ cesky: "naposledy použité (ne lastly...)", anglicky: "recently used" },
	{ cesky: "rozlišovat malá a velká", anglicky: "match case" },
	{ cesky: "rozlišení velkých písmen (ne math)", anglicky: "case sensitivity" },
	{ cesky: "nástrojový pruh", anglicky: "toolbar" },
	{ cesky: "dopředu", anglicky: "forward" },
	{ cesky: "dozadu", anglicky: "backward" },
	{ cesky: "tabulkový procesor", anglicky: "spreadsheet" },
	{ cesky: "buňka tabulky", anglicky: "cell" },
	{ cesky: "zadávat data", anglicky: "enter data" },
	{ cesky: "desetinná místa", anglicky: "decimal places" },
	{ cesky: "zalamování textu", anglicky: "text wrapping" },
	{ cesky: "přetékat (do sousedních buněk)", anglicky: "overflow" },
	{ cesky: "rovnítko", anglicky: "equal sign" },
	{ cesky: "operátor dělení", anglicky: "division operator" },
	{ cesky: "operátor sčítání", anglicky: "addition operator" },
	{ cesky: "odčítání", anglicky: "subtraction" },
	{ cesky: "větší než", anglicky: "greater than" },
	{ cesky: "roven", anglicky: "equal to" },
	{ cesky: "menší než", anglicky: "less than" },
	{ cesky: "není roven", anglicky: "not equal to" },
	{ cesky: "odkaz na buňku", anglicky: "cell reference" },
	{ cesky: "koláčový, výsečový graf", anglicky: "pie chart" },
	{ cesky: "dlaždice", anglicky: "tile" },
	{ cesky: "zvětšení (ne zoom, enlargement)", anglicky: "magnification" },
	{ cesky: "seřadit podle (ne arrange)", anglicky: "sort by" },
	{ cesky: "vzestupně (seřadit)", anglicky: "ascending" },
	{ cesky: "sestupně (seřadit)", anglicky: "descending" }
	],
	
	3: [ /* Slova pro lekci 3 */
	{ cesky: "víko (notebooku)", anglicky: "lid" },
	{ cesky: "spánek", anglicky: "sleep" },
	{ cesky: "známý", anglicky: "known" },
	{ cesky: "omezení (ne constraints, limit)", anglicky: "restriction" },
	{ cesky: "patřit", anglicky: "belong" },
	{ cesky: "jedinečný", anglicky: "unique" },
	{ cesky: "přiřazení", anglicky: "assignment" },
	{ cesky: "vypršet", anglicky: "expire" },
	{ cesky: "pasivovat, zneschopnit (ne disable)", anglicky: "inhibit" },
	{ cesky: "práva", anglicky: "rights" },
	{ cesky: "zrušit (ne discard, cancel)", anglicky: "revoke" },
	{ cesky: "všichni (ne all)", anglicky: "everyone" },
	{ cesky: "skupina, seskupit", anglicky: "group" },
	{ cesky: "řada, fronta", anglicky: "queue" },
	{ cesky: "stav", anglicky: "status" },
	{ cesky: "připojit (ne join, connect, link)", anglicky: "attach" },
	{ cesky: "přihlásit", anglicky: "log in" },
	{ cesky: "uvědomit", anglicky: "notify" },
	{ cesky: "služba", anglicky: "service" },
	{ cesky: "rovný s rovným", anglicky: "peer-to-peer" },
	{ cesky: "vetřelec", anglicky: "intruder" },
	{ cesky: "uzamčení", anglicky: "lockout" },
	{ cesky: "nouze, havárie", anglicky: "emergency" },
	{ cesky: "malé zdokonalení programu", anglicky: "update" },
	{ cesky: "zůstat (ne stay)", anglicky: "remain" },
	{ cesky: "potlačit", anglicky: "suppress" },
	{ cesky: "popis", anglicky: "description" },
	{ cesky: "odmítnout (ne refuse)", anglicky: "reject" },
	{ cesky: "zadržet (ne retain)", anglicky: "hold" },
	{ cesky: "odsunout, pozdržet", anglicky: "defer" },
	{ cesky: "pořadí (ne order)", anglicky: "sequence" },
	{ cesky: "zařadit tisk. úlohu do fronty", anglicky: "submit print job" },
	{ cesky: "podle", anglicky: "according to" },
	{ cesky: "vzor, maska hledání", anglicky: "search pattern" },
	{ cesky: "pověřenec, důvěrník", anglicky: "trustee" },
	{ cesky: "zrušit, stornovat (ne cancel)", anglicky: "discard" },
	{ cesky: "oddělovač (položek seznamu)", anglicky: "delimiter" },
	{ cesky: "vyhrazený", anglicky: "dedicated" },
	{ cesky: "kopie (ne copy)", anglicky: "replica" },
	{ cesky: "včetně", anglicky: "including" },
	{ cesky: "výhoda", anglicky: "advantage" },
	{ cesky: "bez ohledu na", anglicky: "regardless" },
	{ cesky: "dříve než", anglicky: "prior to" },
	{ cesky: "týkající se (ne concerning)", anglicky: "regarding" },
	{ cesky: "podezřívat", anglicky: "suspect" },
	{ cesky: "ztráta", anglicky: "loss" },
	{ cesky: "čitelný", anglicky: "legible" },
	{ cesky: "přibližný", anglicky: "approximate" },
	{ cesky: "trpět", anglicky: "suffer" },
	{ cesky: "zlepšit", anglicky: "improve" },
	{ cesky: "týkat se (ne regard)", anglicky: "concern" },
	{ cesky: "účel", anglicky: "purpose" },
	{ cesky: "odhadnout", anglicky: "estimate" },
	{ cesky: "uzel", anglicky: "node" },
	{ cesky: "dotaz (ne request, question)", anglicky: "query" },
	{ cesky: "spolehlivost", anglicky: "reliability" },
	{ cesky: "vydání (ne issue, release)", anglicky: "edition" },
	{ cesky: "za předpokladu", anglicky: "providing" },
	{ cesky: "dodávka", anglicky: "delivery" },
	{ cesky: "moudrý, rozumný (ne reasonable)", anglicky: "wise" },
	{ cesky: "porušit, přestoupit", anglicky: "violate" },
	{ cesky: "smysl", anglicky: "sense" },
	{ cesky: "prospěch", anglicky: "benefit" },
	{ cesky: "vyvolat (ne invoke)", anglicky: "excite" },
	{ cesky: "nabídnout", anglicky: "offer" },
	{ cesky: "zahrnovat( ne include, contain)", anglicky: "comprise" },
	{ cesky: "chod, tempo", anglicky: "pace" },
	{ cesky: "nezbytný, nutný", anglicky: "necessary" },
	{ cesky: "žádost, požadavek (ne request)", anglicky: "demand" },
	{ cesky: "podobný (ne like)", anglicky: "similar" },
	{ cesky: "spojit, připojit (ne attach, link)", anglicky: "join" },
	{ cesky: "dodavatel, obchodník", anglicky: "vendor" },
	{ cesky: "způsob (ne way)", anglicky: "manner" },
	{ cesky: "důvod", anglicky: "reason" },
	{ cesky: "sídlit", anglicky: "reside" },
	{ cesky: "sada, komplet (ne set, kit)", anglicky: "suite" },
	{ cesky: "sada, komplet (ne set, suite)", anglicky: "kit" },
	{ cesky: "úroveň (ne level)", anglicky: "grade" },
	{ cesky: "sledovaní událostí", anglicky: "auditing" },
	{ cesky: "letní čas", anglicky: "daylight saving time" },
	{ cesky: "předávání", anglicky: "forwarding" },
	{ cesky: "rámec (protokolový)", anglicky: "frame" },
	{ cesky: "protokolový soubor", anglicky: "log file" },
	{ cesky: "důležitý, základní, hlavní", anglicky: "fundamental" },
	{ cesky: "využívat (ne use, utilize)", anglicky: "take advantage" },
	{ cesky: "využívat (ne use, take advantage)", anglicky: "utilize" },
	{ cesky: "nezávislý, samostatný", anglicky: "independent" },
	{ cesky: "zdali", anglicky: "whether" },
	{ cesky: "popisovat", anglicky: "describe" },
	{ cesky: "umístit (ne place, deploy)", anglicky: "locate" },
	{ cesky: "hlavní (ne fundamental, main)", anglicky: "major" },
	{ cesky: "provádět, zpracovávat (ne execute)", anglicky: "process" },
	{ cesky: "nefunkční", anglicky: "inoperable" },
	{ cesky: "přímý, nasměrovat", anglicky: "direct" },
	{ cesky: "zkratka (ne shortcut)", anglicky: "abbreviation" },
	{ cesky: "rozlišovat", anglicky: "distinguish" },
	{ cesky: "odlišný (ne alternate)", anglicky: "different" },
	{ cesky: "shromáždit (ne collect)", anglicky: "gather" },
	{ cesky: "odpovědnost", anglicky: "responsibility" },
	{ cesky: "vrstva", anglicky: "layer" },
	{ cesky: "termín", anglicky: "term" },
	{ cesky: "výstraha, pozornost, opatrnost)", anglicky: "caution" },
	{ cesky: "po dokončení", anglicky: "upon completion" },
	{ cesky: "široké spektrum", anglicky: "wide range" },
	{ cesky: "ladit", anglicky: "tune" },
	{ cesky: "příkaz (v programu)", anglicky: "statement" },
	{ cesky: "příkaz, povel (např. v MSDOS)", anglicky: "command" },
	{ cesky: "náhodný (ve významu nehody)", anglicky: "accidental" },
	{ cesky: "příležitostný, náhodný (ne random)", anglicky: "occasional" },
	{ cesky: "příležitostný, náhodný (ne occas)", anglicky: "random" }
	],
	
	4: [
	{ cesky: "přístrojová deska", anglicky: "dashboard" },
	{ cesky: "přesný (ne precise)", anglicky: "exact" },
	{ cesky: "celkový (ne total)", anglicky: "overall" },
	{ cesky: "různý (ne different, miscellaneous)", anglicky: "various" },
	{ cesky: "předpokládat", anglicky: "suppose" },
	{ cesky: "poznat", anglicky: "recognize" },
	{ cesky: "postup, pokrok (ne progress)", anglicky: "advance" },
	{ cesky: "proveditelný", anglicky: "executable" },
	{ cesky: "umístěný (ne located)", anglicky: "placed" },
	{ cesky: "tok (ne stream)", anglicky: "flow" },
	{ cesky: "spustit, uvést v chod", anglicky: "launch" },
	{ cesky: "zvýraznit (ne mark)", anglicky: "highlight" },
	{ cesky: "kromě (ne besides)", anglicky: "except" },
	{ cesky: "složený", anglicky: "compound" },
	{ cesky: "za, mimo, nad", anglicky: "beyond" },
	{ cesky: "obejít (ne override)", anglicky: "bypass" },
	{ cesky: "úsilí, snaha", anglicky: "effort" },
	{ cesky: "stálý, trvalý (ne parmanent)", anglicky: "persistent" },
	{ cesky: "používat, využívat (ne use, utilize)", anglicky: "facilitate" },
	{ cesky: "zastaralý (ne outdated, legacy)", anglicky: "obsolete" },
	{ cesky: "v souladu s", anglicky: "consistent with" },
	{ cesky: "odpovídat čemu, splňovat", anglicky: "comply with" },
	{ cesky: "hlavní panel", anglicky: "taskbar" },
	{ cesky: "provést (ne perform, execute, accomplish)", anglicky: "commit" },
	{ cesky: "získat (ne obtain, gain, acquire)", anglicky: "gather" },
	{ cesky: "získat (ne get, gather, acquire)", anglicky: "obtain" },
	{ cesky: "získat (ne gain, get, obtain)", anglicky: "acquire" },
	{ cesky: "získat (ne acquire, obtain, get)", anglicky: "gain" },
	{ cesky: "současný", anglicky: "concurrent" },
	{ cesky: "připojení (ne link)", anglicky: "connection" },
	{ cesky: "samostatný", anglicky: "stand alone" },
	{ cesky: "drátem připojený", anglicky: "wired" },
	{ cesky: "vazba, provázání", anglicky: "binding" },
	{ cesky: "pořadí prohledávání", anglicky: "search order" },
	{ cesky: "výkon (ne power)", anglicky: "performance" },
	{ cesky: "poslat", anglicky: "send" },
	{ cesky: "nepřerušitelný", anglicky: "uninterruptible" },
	{ cesky: "zdroj napájení", anglicky: "power supply" },
	{ cesky: "vybitá baterie", anglicky: "low battery" },
	{ cesky: "místní (ne native)", anglicky: "local" },
	{ cesky: "doba trvání hesla", anglicky: "password age" },
	{ cesky: "povolit (ne allow, approve)", anglicky: "permit" },
	{ cesky: "rozprostřený", anglicky: "distributed" },
	{ cesky: "nečinný", anglicky: "idle" },
	{ cesky: "poslední známý", anglicky: "last known" },
	{ cesky: "cestovat, toulat se", anglicky: "roam" },
	{ cesky: "oznamovací tón", anglicky: "dial tone" },
	{ cesky: "vyloučit oblast (ne area)", anglicky: "exclude range" },
	{ cesky: "automatizovat", anglicky: "automate" },
	{ cesky: "zavěsit, odpojit linku", anglicky: "hang up" },
	{ cesky: "vysílat (ne broadcast)", anglicky: "transmit" },
	{ cesky: "výzva, náročný úkol (ne prompt)", anglicky: "challenge" },
	{ cesky: "odezva, reakce (ne reaction)", anglicky: "response" },
	{ cesky: "odpovídat na, reagovat", anglicky: "respond to" },
	{ cesky: "trvání propůjčení", anglicky: "lease duration" },
	{ cesky: "důvěřovat", anglicky: "trust" },
	{ cesky: "nejvíce omezující", anglicky: "most restrictive" },
	{ cesky: "omezit přístup (ne deny)", anglicky: "restrict access" },
	{ cesky: "bezobslužný, bez přítomnosti", anglicky: "unattended" },
	{ cesky: "být přítomen", anglicky: "attend" },
	{ cesky: "volba (ne selection, choice)", anglicky: "option" },
	{ cesky: "ověření (ne authentication, verify)", anglicky: "validation" },
	{ cesky: "mouse, mn.č.", anglicky: "mice" },
	{ cesky: "průchodnost", anglicky: "throughput" },
	{ cesky: "závažný (ne serious)", anglicky: "severe" },
	{ cesky: "jednoduchý", anglicky: "simple" },
	{ cesky: "udržovat, zachovat", anglicky: "maintain" },
	{ cesky: "údržba", anglicky: "maintenance" },
	{ cesky: "volba (ne option, choice)", anglicky: "selection" },
	{ cesky: "navrhovat (ne suggest)", anglicky: "propose" },
	{ cesky: "nasadit, zavést do praxe, realizovat", anglicky: "implement" },
	{ cesky: "poskytovat", anglicky: "provide" },
	{ cesky: "zvýšit", anglicky: "increase" },
	{ cesky: "prozradit, odkrýt", anglicky: "reveal" },
	{ cesky: "režie", anglicky: "overhead" },
	{ cesky: "doručit, dodat", anglicky: "deliver" },
	{ cesky: "simulovat", anglicky: "emulate" },
	{ cesky: "poškodit", anglicky: "damage" },
	{ cesky: "odstranit, vyloučit (ne exclude)", anglicky: "eliminate" },
	{ cesky: "schopnost (ne ability)", anglicky: "capability" },
	{ cesky: "citlivý", anglicky: "sensitive" },
	{ cesky: "výrazný (ne highlighted)", anglicky: "considerable" },
	{ cesky: "zachovat si, ponechat (ne preserve)", anglicky: "retain" },
	{ cesky: "zachovat, uchovat (ne retain)", anglicky: "preserve" },
	{ cesky: "efektivní, výkonný", anglicky: "efficient" },
	{ cesky: "rozpětí, rozsah (ne scope, range)", anglicky: "span" },
	{ cesky: "pravidelný", anglicky: "regular" },
	{ cesky: "potkat (ne meet)", anglicky: "encounter" },
	{ cesky: "všeobecně použitelný", anglicky: "generic" },
	{ cesky: "způsobovat, důvod, příčina", anglicky: "cause" },
	{ cesky: "čekající na vyřízení", anglicky: "pending" },
	{ cesky: "vyhnout se", anglicky: "avoid" },
	{ cesky: "obejít (ne bypass)", anglicky: "override" },
	{ cesky: "použitelný (ne usable)", anglicky: "applicable" },
	{ cesky: "podmnožina", anglicky: "subset" },
	{ cesky: "zajistit (ne ensure, assert)", anglicky: "guarantee" },
	{ cesky: "zajistit(ne ensure, guarantee)", anglicky: "assert" },
	{ cesky: "zajistit(ne assert, guarantee)", anglicky: "ensure" },
	{ cesky: "zatížení, důraz", anglicky: "stress" },
	{ cesky: "zacházet, manipulovat (ne manipulate)", anglicky: "handle" },
	{ cesky: "měřit", anglicky: "measure" },
	{ cesky: "čítač", anglicky: "counter" },
	{ cesky: "loudavý", anglicky: "sluggish" },
	{ cesky: "přílišný", anglicky: "excessive" },
	{ cesky: "uváznutý", anglicky: "stuck" },
	{ cesky: "volný (ne free)", anglicky: "loose" },
	{ cesky: "zničený, porušený (ne damaged)", anglicky: "corrupt(ed)" },
	{ cesky: "vyrovnávací paměť", anglicky: "buffer" },
	{ cesky: "všesměrový paket", anglicky: "broadcast" },
	{ cesky: "vyrovnávání zatížení", anglicky: "load balancing" },
	{ cesky: "řešení jména", anglicky: "name resolution" },
	{ cesky: "dopředné čtení", anglicky: "read ahead" },
	{ cesky: "dědění práv", anglicky: "rights inheritance" },
	{ cesky: "přípojka (port)", anglicky: "socket" },
	{ cesky: "odkládací soubor", anglicky: "swap file" }
	],
	5: [
	{ cesky: "dosáhnout (ne reach)", anglicky: "achieve" },
	{ cesky: "výstraha, poplach", anglicky: "alert" },
	{ cesky: "pokračovat (ne proceed, resume)", anglicky: "continue" },
	{ cesky: "podnikový, firemní", anglicky: "corporate" },
	{ cesky: "cíl", anglicky: "destination" },
	{ cesky: "určit, rozhodnout (ne decide)", anglicky: "determine" },
	{ cesky: "vybavený", anglicky: "equipped" },
	{ cesky: "odchozí", anglicky: "outbound" },
	{ cesky: "zastaralý, starší verze (ne obsolete)", anglicky: "outdated" },
	{ cesky: "stálý, trvalý (ne persistent)", anglicky: "permanent" },
	{ cesky: "připravovat", anglicky: "prepare" },
	{ cesky: "dosáhnout (ne achieve)", anglicky: "reach" },
	{ cesky: "předložit, podat", anglicky: "submit" },
	{ cesky: "dočasný", anglicky: "temporary" },
	{ cesky: "jednotka", anglicky: "unit" },
	{ cesky: "využití (ne usage)", anglicky: "utilization" },
	{ cesky: "most", anglicky: "bridge" },
	{ cesky: "knoflík, tlačítko", anglicky: "button" },
	{ cesky: "žádoucí, vhodný", anglicky: "desired" },
	{ cesky: "přípona, prodloužení", anglicky: "extension" },
	{ cesky: "často (ne often)", anglicky: "frequently" },
	{ cesky: "vstup (ne entry)", anglicky: "input" },
	{ cesky: "položka", anglicky: "item" },
	{ cesky: "zámek, ochrana", anglicky: "protection" },
	{ cesky: "nedávný, minulý (ne last, previous)", anglicky: "recent" },
	{ cesky: "uskutečnit, vykonat (ne execute)", anglicky: "accomplish" },
	{ cesky: "odpovídající, splňující požadavek", anglicky: "compliant" },
	{ cesky: "soulad s, vyhovění čemu, dodržovat", anglicky: "compliance" },
	{ cesky: "potvrdit (ne acknowledge)", anglicky: "confirm" },
	{ cesky: "podnik", anglicky: "enterprise" },
	{ cesky: "povinný (ne obligatory)", anglicky: "mandatory" },
	{ cesky: "zakázaný(ne denied, restricted)", anglicky: "prohibited" },
	{ cesky: "oprava, opravit (ne correction)", anglicky: "repair" },
	{ cesky: "špatný", anglicky: "wrong" },
	{ cesky: "prohlížet", anglicky: "browse" },
	{ cesky: "okolí, prostředí", anglicky: "environment" },
	{ cesky: "spustit, vykonat (ne perform, launch)", anglicky: "execute" },
	{ cesky: "určitý, konkrétní (ne specific)", anglicky: "particular" },
	{ cesky: "oblast (ne area, scope)", anglicky: "range" },
	{ cesky: "výsledek", anglicky: "result" },
	{ cesky: "podpis", anglicky: "signature" },
	{ cesky: "zdroj (ne supply, resource)", anglicky: "source" },
	{ cesky: "zdroj (ne supply, source)", anglicky: "resource" },
	{ cesky: "zdroj (ne resource, source)", anglicky: "supply" },
	{ cesky: "pruh", anglicky: "stripe" },
	{ cesky: "trasa, následovat", anglicky: "trace" },
	{ cesky: "platný", anglicky: "valid" },
	{ cesky: "hodnota", anglicky: "value" },
	{ cesky: "pozadí", anglicky: "background" },
	{ cesky: "jistý (ne sure)", anglicky: "certain" },
	{ cesky: "výjimka", anglicky: "exception" },
	{ cesky: "neúspěšný (ne unsuccessful)", anglicky: "failed" },
	{ cesky: "pokrok (ne advance)", anglicky: "progress" },
	{ cesky: "za předpokladu, že", anglicky: "provided" },
	{ cesky: "příbuzný", anglicky: "related" },
	{ cesky: "uvolnit (např. tlačítko myši)", anglicky: "release" },
	{ cesky: "řešit", anglicky: "solve" },
	{ cesky: "přes", anglicky: "via" },
	{ cesky: "uvnitř, v mezích", anglicky: "within" },
	{ cesky: "schopnost (ne capability)", anglicky: "ability" },
	{ cesky: "slučitelnost", anglicky: "compatibility" },
	{ cesky: "denně", anglicky: "daily" },
	{ cesky: "položka, vstup (ne input)", anglicky: "entry" },
	{ cesky: "příklad", anglicky: "example" },
	{ cesky: "rychle (ne fast)", anglicky: "quickly" },
	{ cesky: "přijmout  (ne receive)", anglicky: "accept" },
	{ cesky: "příchozí", anglicky: "incoming" },
	{ cesky: "vsunout, vložit", anglicky: "insert" },
	{ cesky: "původní (ne initial)", anglicky: "original" },
	{ cesky: "část (ne part)", anglicky: "portion" },
	{ cesky: "oddělený", anglicky: "separate" },
	{ cesky: "chytrý (ne wise, clever)", anglicky: "smart" },
	{ cesky: "ověření (ne authentication, validation)", anglicky: "verification" },
	{ cesky: "objevit se (ne occur)", anglicky: "appear" },
	{ cesky: "objevit se, nastat (ne appear, happen)", anglicky: "occur" },
	{ cesky: "případ (ne event)", anglicky: "case" },
	{ cesky: "pověření (jméno a konto)", anglicky: "credentials" },
	{ cesky: "zakázat (ne prohibit, restrict)", anglicky: "deny" },
	{ cesky: "režim spánku", anglicky: "hibernation" },
	{ cesky: "spoj, spojit (ne join)", anglicky: "link" },
	{ cesky: "prostředek", anglicky: "means" },
	{ cesky: "bod (ne dot)", anglicky: "point" },
	{ cesky: "společný fond", anglicky: "pool" },
	{ cesky: "obrazovka", anglicky: "screen" },
	{ cesky: "nástroj", anglicky: "tool" },
	{ cesky: "odlišný, alternativní (ne different)", anglicky: "alternate" },
	{ cesky: "odhalení, detekce", anglicky: "detection" },
	{ cesky: "odpojit (ne detach)", anglicky: "disconnect" },
	{ cesky: "správný (ne correct)", anglicky: "proper" },
	{ cesky: "hledat (ne seek, scan, lookup)", anglicky: "search" },
	{ cesky: "odstraňovat chyby (ne debug)", anglicky: "troubleshoot" },
	{ cesky: "množství", anglicky: "amount" },
	{ cesky: "kazeta", anglicky: "cartridge" },
	{ cesky: "připojitelnost, kvalita přip.", anglicky: "connectivity" },
	{ cesky: "zkoumat (ne explore)", anglicky: "examine" },
	{ cesky: "hostitel, hostit", anglicky: "host" },
	{ cesky: "vícenásobný, mnohý", anglicky: "multiple" },
	{ cesky: "násobit", anglicky: "multiply" },
	{ cesky: "poznámka", anglicky: "note" },
	{ cesky: "vlastnictví", anglicky: "ownership" },
	{ cesky: "znovu nastavit", anglicky: "reset" },
	{ cesky: "řešení problémů", anglicky: "troubleshooting" },
	{ cesky: "obsah", anglicky: "content" },
	{ cesky: "umístit, nasadit (ne locate, place)", anglicky: "deploy" },
	{ cesky: "podobně (ne similarly)", anglicky: "likely" },
	{ cesky: "vyjmenovaný, zapsaný v seznamu", anglicky: "listed" },
	{ cesky: "výzva (v přík.řádku), podnět", anglicky: "prompt" },
	{ cesky: "bezpečný (ne secure)", anglicky: "safe" },
	{ cesky: "dodatečný, další", anglicky: "additional" },
	{ cesky: "pruh (ne stripe)", anglicky: "bar" },
	{ cesky: "založený na", anglicky: "based" },
	{ cesky: "šifrovat", anglicky: "encrypt" },
	{ cesky: "rozbočovač", anglicky: "hub" },
	{ cesky: "vydání, vydat (needition, release)", anglicky: "issue" },
	{ cesky: "jazyk", anglicky: "language" },
	{ cesky: "zhustit, stlačit (ne compress)", anglicky: "pack" },
	{ cesky: "oddíl", anglicky: "partition" },
	{ cesky: "technik", anglicky: "technician" },
	{ cesky: "rys, vlastnost (ne property)", anglicky: "feature" },
	{ cesky: "zavést do paměti (ne boot)", anglicky: "load" },
	{ cesky: "umístění", anglicky: "location" },
	{ cesky: "předchozí", anglicky: "previous" },
	{ cesky: "žádat, žádost (ne require, demand)", anglicky: "request" },
	{ cesky: "řešení, překlad, rozlišení", anglicky: "resolution" },
	{ cesky: "kdykoliv", anglicky: "whenever" },
	{ cesky: "zaměstnanec", anglicky: "employee" },
	{ cesky: "zahrnout (ne comprise)", anglicky: "include" }
	],
	6: [
	{ cesky: "přesunout (ne shift)", anglicky: "move" },
	{ cesky: "balíček", anglicky: "package" },
	{ cesky: "osobní", anglicky: "personal" },
	{ cesky: "bez znaménka", anglicky: "unsigned" },
	{ cesky: "vývoj", anglicky: "development" },
	{ cesky: "člen", anglicky: "member" },
	{ cesky: "cesta (k souboru)", anglicky: "path" },
	{ cesky: "sezení", anglicky: "session" },
	{ cesky: "aktuální (ne up to date)", anglicky: "current" },
	{ cesky: "zvyk", anglicky: "custom" },
	{ cesky: "událost (ne case)", anglicky: "event" },
	{ cesky: "obraz", anglicky: "image" },
	{ cesky: "několik (ne some)", anglicky: "several" },
	{ cesky: "zastaralý, starší verze (ne obsolete)", anglicky: "legacy" },
	{ cesky: "tudíž, tedy (ne so, therefore)", anglicky: "thus" },
	{ cesky: "příslušný, odpovídající (ne correct)", anglicky: "appropriate" },
	{ cesky: "přiřadit", anglicky: "assign" },
	{ cesky: "koláček", anglicky: "cookie" },
	{ cesky: "kořen", anglicky: "root" },
	{ cesky: "bezdrátový", anglicky: "wireless" },
	{ cesky: "řadič", anglicky: "controller" },
	{ cesky: "ustavit, založit, zřídit", anglicky: "establish" },
	{ cesky: "uvést, prohlásit", anglicky: "state" },
	{ cesky: "neschopen", anglicky: "unable" },
	{ cesky: "objevit, najít, zjistit (ne find)", anglicky: "discover" },
	{ cesky: "ještě, nadto, kromě toho", anglicky: "furthermore" },
	{ cesky: "soukromý", anglicky: "private" },
	{ cesky: "cestovní (ne travel)", anglicky: "roaming" },
	{ cesky: "úložné místo, paměť", anglicky: "storage" },
	{ cesky: "přepínač, volba", anglicky: "switch" },
	{ cesky: "čaroděj, přeneseně: průvodce", anglicky: "wizard" },
	{ cesky: "ovlivnit", anglicky: "affect" },
	{ cesky: "vymazat (ne erase, clear, remove)", anglicky: "delete" },
	{ cesky: "přírůstkový", anglicky: "incremental" },
	{ cesky: "umístěný (ne placed, deployed)", anglicky: "located" },
	{ cesky: "běžící", anglicky: "running" },
	{ cesky: "řešení", anglicky: "solution" },
	{ cesky: "důvěryhodný", anglicky: "trusted" },
	{ cesky: "ověření při přihlašování", anglicky: "authentication" },
	{ cesky: "klávesa", anglicky: "key" },
	{ cesky: "výzkum", anglicky: "research" },
	{ cesky: "vytočit", anglicky: "dial" },
	{ cesky: "vyřešit, přeložit", anglicky: "resolve" },
	{ cesky: "skrz", anglicky: "through" },
	{ cesky: "zavést op.systém do paměti", anglicky: "boot" },
	{ cesky: "vymazat (ne delete, erase, remove)", anglicky: "clear" },
	{ cesky: "úkol, úloha (ne job)", anglicky: "task" },
	{ cesky: "úspěšně", anglicky: "successfully" },
	{ cesky: "obnovit, aktualizovat (ne restore)", anglicky: "update" },
	{ cesky: "pokus, pokusit se (ne try)", anglicky: "attempt" },
	{ cesky: "vybrat (ne select, pick)", anglicky: "choose" },
	{ cesky: "vyžadovat (ne request, demand)", anglicky: "require" },
	{ cesky: "sestávat se z, skládat se z", anglicky: "consist" },
	{ cesky: "pružný", anglicky: "flexible" },
	{ cesky: "velké zdokonalení programu", anglicky: "upgrade" },
	{ cesky: "správce", anglicky: "manager" },
	{ cesky: "pokročilý", anglicky: "advanced" },
	{ cesky: "změnit", anglicky: "change" },
	{ cesky: "spravovat, řídit (ne control)", anglicky: "manage" },
	{ cesky: "zpráva, hlásit", anglicky: "report" },
	{ cesky: "mezera, prostor", anglicky: "space" },
	{ cesky: "záložka (listu v Excelu)", anglicky: "tab" },
	{ cesky: "použít, aplikovat (ne use)", anglicky: "apply" },
	{ cesky: "ovladač", anglicky: "driver" },
	{ cesky: "dělit se o, sdílet", anglicky: "share" },
	{ cesky: "provést (ne commit, execute)", anglicky: "perform" },
	{ cesky: "směrovač", anglicky: "router" },
	{ cesky: "rozhraní", anglicky: "interface" },
	{ cesky: "zabránit čemu", anglicky: "prevent from" },
	{ cesky: "přesměrovat (ne re-route)", anglicky: "redirect" },
	{ cesky: "od (časově)", anglicky: "since" },
	{ cesky: "podpora, podporovat", anglicky: "support" },
	{ cesky: "ověřit si, prověřit", anglicky: "verify" },
	{ cesky: "nastavení (ne setting)", anglicky: "setup" },
	{ cesky: "odstranit( ne erase, delete, clean)", anglicky: "remove" },
	{ cesky: "jednotlivý, osamocený, samostatný", anglicky: "single" },
	{ cesky: "brána", anglicky: "gateway" },
	{ cesky: "režim", anglicky: "mode" },
	{ cesky: "podsíť", anglicky: "subnet" },
	{ cesky: "použít", anglicky: "use" },
	{ cesky: "následující (ne next)", anglicky: "following" },
	{ cesky: "svazek", anglicky: "volume" },
	{ cesky: "k dispozici, dostupný", anglicky: "available" },
	{ cesky: "darovat, přidělit, pověřit", anglicky: "grant" },
	{ cesky: "proto, tudíž, takže (ne thus, so)", anglicky: "therefore" },
	{ cesky: "obdržet, přijmout, dostat (ne accept)", anglicky: "receive" },
	{ cesky: "obnovit ze zálohy (ne recovery)", anglicky: "restore" },
	{ cesky: "heslo", anglicky: "password" },
	{ cesky: "předvést, ukázat, vystavit, ukázka", anglicky: "exhibit" },
	{ cesky: "adresář (ne složka -folder)", anglicky: "directory" },
	{ cesky: "vlastnost (ne feature)", anglicky: "property" },
	{ cesky: "upravit, změnit (ne edit, change)", anglicky: "modify" },
	{ cesky: "průzkumník", anglicky: "explorer" },
	{ cesky: "záloha", anglicky: "backup" },
	{ cesky: "pasivovat, zneschopnit (ne inhibit)", anglicky: "disable" },
	{ cesky: "zpráva (ne report)", anglicky: "message" },
	{ cesky: "nastavení (ne setup)", anglicky: "setting" },
	{ cesky: "řídit (ne manage)", anglicky: "control" },
	{ cesky: "testovat, ověřit (ne test, verify)", anglicky: "check" },
	{ cesky: "konto", anglicky: "account" },
	{ cesky: "výpis, seznam", anglicky: "list" },
	{ cesky: "chyba (ne fault, failure, mistake)", anglicky: "error" },
	{ cesky: "odpojená tiskárna (ne disconnect)", anglicky: "offline" },
	{ cesky: "záznam (ne record)", anglicky: "log" },
	{ cesky: "větev", anglicky: "branch" },
	{ cesky: "stanoviště", anglicky: "site" },
	{ cesky: "volitelný", anglicky: "optional" },
	{ cesky: "zařízení (ne equipment)", anglicky: "device" },
	{ cesky: "připojit (ne attach, join, add)", anglicky: "connect" },
	{ cesky: "vzdálený", anglicky: "remote" },
	{ cesky: "připojit, doplnit( ne join,append)", anglicky: "add" },
	{ cesky: "přenosný", anglicky: "portable" },
	{ cesky: "vytvořit", anglicky: "create" },
	{ cesky: "povolení, oprávnění", anglicky: "permission" },
	{ cesky: "předem nastavený (ne preset)", anglicky: "default" },
	{ cesky: "umožnit (ne allow)", anglicky: "enable" },
	{ cesky: "povolit (ne permit, approve)", anglicky: "allow" },
	{ cesky: "bezpečnost (ne safety)", anglicky: "security" },
	{ cesky: "přístup", anglicky: "access" },
	{ cesky: "složka (ne directory)", anglicky: "folder" },
	{ cesky: "soubor", anglicky: "file" },
	{ cesky: "uživatel", anglicky: "user" },
	{ cesky: "stát se současně (ne coincide)", anglicky: "collide" }
	],
	7: [
	{ cesky: "přenos", anglicky: "transfer" },
	{ cesky: "obecný, běžný, obvyklý", anglicky: "common" },
	{ cesky: "stoh, zásobník", anglicky: "stack" },
	{ cesky: "potvrdit např. příjem (ne confirm)", anglicky: "acknowledge" },
	{ cesky: "potřesení rukou", anglicky: "handshake" },
	{ cesky: "nedostupný (ne unavailable)", anglicky: "unreachable" },
	{ cesky: "překročit", anglicky: "exceed" },
	{ cesky: "pročistit (doslova spláchnout)", anglicky: "flush" },
	{ cesky: "sada protokolů", anglicky: "protocol suite" },
	{ cesky: "vytáčené spojení", anglicky: "dial-up connection" },
	{ cesky: "zásuvný modul", anglicky: "snap-in" },
	{ cesky: "délka", anglicky: "length" },
	{ cesky: "přenášet, předat dál (ne transmit)", anglicky: "relay" },
	{ cesky: "občerstvit", anglicky: "refresh" },
	{ cesky: "nadřazená (rodičovská) složka", anglicky: "parent folder" },
	{ cesky: "zpětné hledání", anglicky: "reverse lookup" },
	{ cesky: "podmíněný", anglicky: "conditional" },
	{ cesky: "odpověď", anglicky: "answer" },
	{ cesky: "zděděný", anglicky: "inherited" },
	{ cesky: "řízení přístupu", anglicky: "access control" },
	{ cesky: "zřídit spojení", anglicky: "set up a connection" },
	{ cesky: "překlad", anglicky: "translation" },
	{ cesky: "pořadí zpracování", anglicky: "processing order" },
	{ cesky: "na vyžádání", anglicky: "on demand" },
	{ cesky: "vynutit", anglicky: "enforce" },
	{ cesky: "harmonogram, časový plán", anglicky: "schedule" },
	{ cesky: "zamýšlený účel", anglicky: "intended purpose" },
	{ cesky: "registrace (ne registration)", anglicky: "enrolment" },
	{ cesky: "označit (ne highlight - zvýraznit)", anglicky: "mark" },
	{ cesky: "vydavatel", anglicky: "publisher" },
	{ cesky: "karanténa", anglicky: "quarantine" },
	{ cesky: "způsobilý, oprávněný k čemu", anglicky: "eligible" },
	{ cesky: "selftest", anglicky: "selftest" },
	{ cesky: "schválit (ne allow, permit)", anglicky: "approve" },
	{ cesky: "uspořádat (ne sort)", anglicky: "arrange" },
	{ cesky: "spojení (ne link, connection)", anglicky: "association" },
	{ cesky: "zachytit, zaznamenat", anglicky: "capture" },
	{ cesky: "čištění", anglicky: "cleanup" },
	{ cesky: "stát se současně, shodovat se s", anglicky: "coincide" },
	{ cesky: "sbírat (ne gather, pick)", anglicky: "collect" },
	{ cesky: "obsahovat", anglicky: "contain" },
	{ cesky: "jádro", anglicky: "core" },
	{ cesky: "využití procesoru", anglicky: "CPU utilization" },
	{ cesky: "prodleva", anglicky: "delay" },
	{ cesky: "záviset na", anglicky: "depend on" },
	{ cesky: "odvozený od", anglicky: "derived from" },
	{ cesky: "navrhovat (např. síť)", anglicky: "design" },
	{ cesky: "trvání", anglicky: "duration" },
	{ cesky: "vymáhání, vynucení", anglicky: "enforcement" },
	{ cesky: "zapsat do seznamu, zaregistrovat", anglicky: "enlist" },
	{ cesky: "výčet, vyjmenování", anglicky: "enumeration" },
	{ cesky: "vyhodnotit, ověřit, posoudit", anglicky: "evaluate" },
	{ cesky: "identifikovat, určit, zjistit", anglicky: "identify" },
	{ cesky: "okamžitě", anglicky: "immediately" },
	{ cesky: "směřující dovnitř, příchozí", anglicky: "inbound" },
	{ cesky: "inventura", anglicky: "inventory" },
	{ cesky: "latence, zdržení", anglicky: "latency" },
	{ cesky: "monitorovat, sledovat (ne observe)", anglicky: "monitor" },
	{ cesky: "připojit (např. disk, ne connect)", anglicky: "mount" },
	{ cesky: "vyjednávání (např. o protokolu)", anglicky: "negotiation" },
	{ cesky: "pořadí (ne sequence)", anglicky: "order" },
	{ cesky: "táhnout (ne drag)", anglicky: "pull" },
	{ cesky: "vyčistit, vymazat (ne clean)", anglicky: "purge" },
	{ cesky: "snížit, redukovat", anglicky: "reduce" },
	{ cesky: "řešit (překládat) dotazy (DNS)", anglicky: "resolve queries" },
	{ cesky: "získat zpět, vrátit, vyzvednout", anglicky: "retrieve" },
	{ cesky: "zjistit, vyhledat informaci", anglicky: "retrieve" },
	{ cesky: "pravidlo", anglicky: "rule" },
	{ cesky: "uspokojit požadavek", anglicky: "satisfy requirement" },
	{ cesky: "načasovaný, s nast. časem spuštěn", anglicky: "scheduled" },
	{ cesky: "rozštěpený, rozdělený", anglicky: "split" },
	{ cesky: "starý, neplatný (ne outdated, obsolete)", anglicky: "stale" },
	{ cesky: "provoz přenášených dat", anglicky: "transfer traffic" },
	{ cesky: "přechod", anglicky: "transition" },
	{ cesky: "spouštěcí akce", anglicky: "trigger" },
	{ cesky: "ověřit kým (ne verify by)", anglicky: "validate by" },
	{ cesky: "zahájit", anglicky: "initiate" },
	{ cesky: "považovat", anglicky: "consider" },
	{ cesky: "neočekávaně", anglicky: "unexpectedly" },
	{ cesky: "vyvolávat co (ne excite)", anglicky: "invoke" },
	{ cesky: "důvěrný", anglicky: "confidential" },
	{ cesky: "sledovat co, dodržovat co", anglicky: "observe" },
	{ cesky: "vyřadit z provozu", anglicky: "decommission" },
	{ cesky: "účinek (ne effect)", anglicky: "impact" },
	{ cesky: "vyjmenovat, vyčíslit", anglicky: "enumerate" },
	{ cesky: "odběr, předplatné", anglicky: "subscription" },
	{ cesky: "vzájemný, oboustranný", anglicky: "mutual" },
	{ cesky: "šířka pásma", anglicky: "bandwidth" },
	{ cesky: "práh", anglicky: "threshold" },
	{ cesky: "náhrobek, záznam o smazaném", anglicky: "tombstone" },
	{ cesky: "úvodní byte", anglicky: "preamble byte" }
	],
	8: [
	{ cesky: "přerušit, ukončit (ne break, interrupt)", anglicky: "abort" },
	{ cesky: "připojit na konec, doplnit", anglicky: "append" },
	{ cesky: "porovnat", anglicky: "compare" },
	{ cesky: "podmínka", anglicky: "condition" },
	{ cesky: "odstraňovat chyby (ne troubleshoot)", anglicky: "debug" },
	{ cesky: "výraz (ne statement = příkaz)", anglicky: "expression" },
	{ cesky: "hromada, halda", anglicky: "heap" },
	{ cesky: "odsadit (při psaní)", anglicky: "indent" },
	{ cesky: "záznam, věta", anglicky: "record" },
	{ cesky: "odkaz, zmínka (ne referral)", anglicky: "reference" },
	{ cesky: "odkaz (ne reference, link)", anglicky: "referral" },
	{ cesky: "rozsah, rozsah platnosti (ne span, range)", anglicky: "scope" },
	{ cesky: "přerušit (ne pause, interrupt, abort)", anglicky: "suspend" },
	{ cesky: "proměnná", anglicky: "variable" },
	{ cesky: "uvozovky", anglicky: "double quotes" },
	{ cesky: "' (apostrof)", anglicky: "single quotes" },
	{ cesky: "kontrola, zda něco páruje", anglicky: "pair matching" },
	{ cesky: "krokovat program (ne debug)", anglicky: "trace" },
	{ cesky: "ukázat (ne point)", anglicky: "show" },
	{ cesky: "krok", anglicky: "step" },
	{ cesky: "bod přerušení", anglicky: "breakpoint" },
	{ cesky: "vyhodnocení logického výrazu", anglicky: "boolean evaluation" },
	{ cesky: "podmíněný příkaz (ne command)", anglicky: "conditional statement" },
	{ cesky: "vnořená smyčka", anglicky: "nested loop" },
	{ cesky: "vývojový diagram", anglicky: "flow chart" },
	{ cesky: "ukázat (ne show)", anglicky: "point" },
	{ cesky: "ukazatel", anglicky: "pointer" },
	{ cesky: "dědičnost", anglicky: "inheritance" },
	{ cesky: "nasazení", anglicky: "deployment" },
	{ cesky: "proud (ne flow)", anglicky: "stream" },
	{ cesky: "překladač", anglicky: "compiler" },
	{ cesky: "příznak", anglicky: "flag" },
	{ cesky: "spojit (řetězce)", anglicky: "concatenate" },
	{ cesky: "zásobník volání", anglicky: "call stack" },
	{ cesky: "zaváděcí program", anglicky: "loader" },
	{ cesky: "pasivovaný", anglicky: "disabled" },
	{ cesky: "start", anglicky: "startup" },
	{ cesky: "jinak", anglicky: "else" },
	{ cesky: "smyčka", anglicky: "loop" },
	{ cesky: "zatímco", anglicky: "while" },
	{ cesky: "spodní mez", anglicky: "lower bound" },
	{ cesky: "výstup", anglicky: "output" },
	{ cesky: "#", anglicky: "hash" },
	{ cesky: "ladicí program", anglicky: "debugger" },
	{ cesky: "počet", anglicky: "count" },
	{ cesky: "zdrojový soubor", anglicky: "source file" },
	{ cesky: "podařit se", anglicky: "succeed" },
	{ cesky: "vyjmout, vyloučit (ne eliminate)", anglicky: "exclude" },
	{ cesky: "zahrnout, obsahovat (ne contain)", anglicky: "include" },
	{ cesky: "strop", anglicky: "ceiling" },
	{ cesky: "podlaha", anglicky: "floor" },
	{ cesky: "síla, výkon (ne performance)", anglicky: "power" },
	{ cesky: "návěští", anglicky: "label" },
	{ cesky: "varování", anglicky: "warning" },
	{ cesky: "vrátit (ne retrieve)", anglicky: "return" },
	{ cesky: "neplatný (ne invalid)", anglicky: "void" },
	{ cesky: "rezervace místa v paměti", anglicky: "memory allocation" },
	{ cesky: "nekonečno", anglicky: "infinity" },
	{ cesky: "přetečení", anglicky: "overflow" },
	{ cesky: "zabalit (ne pack)", anglicky: "wrap" },
	{ cesky: "ignorovat rozdíl mezi velikostí písmen", anglicky: "ignore case" },
	{ cesky: "čekat", anglicky: "wait" },
	{ cesky: "ukončit (ne break, abort, finish)", anglicky: "terminate" },
	{ cesky: "sekvence volání", anglicky: "call sequence" },
	{ cesky: "různý, rozličný (ne various)", anglicky: "miscellaneous" },
	{ cesky: "hranice, okraj (ne outline:obrys)", anglicky: "border" },
	{ cesky: "omezení (ne restriction, limit)", anglicky: "constraints" },
	{ cesky: "výška", anglicky: "height" },
	{ cesky: "šířka", anglicky: "width" },
	{ cesky: "s měnitelným rozměrem", anglicky: "resizable" },
	{ cesky: "pole  (ne field)", anglicky: "array" },
	{ cesky: "interpunkční znaménko", anglicky: "punctuation" },
	{ cesky: "přírůstek", anglicky: "increment" },
	{ cesky: "větvení", anglicky: "choice" },
	{ cesky: "srovnání", anglicky: "comparison" },
	{ cesky: "zdrojový kód", anglicky: "source code" },
	{ cesky: "kontrola, kontrolovat", anglicky: "check" },
	{ cesky: "prohození, prohodit", anglicky: "swap" },
	{ cesky: "řešení", anglicky: "solution" },
	{ cesky: "vnořený příkaz if", anglicky: "cascading if statement" },
	{ cesky: "naplnit pole", anglicky: "populate an array" },
	{ cesky: "rozhodovací příkaz", anglicky: "decision statement" }
	]
};